name: app-c
on:
  push:
    # run this workflow when files inside app-c change
    # or this workflow file changes
    # or the root package.json file changes
    paths:
      - 'apps/app-c/**'
      - package.json
      - .github/workflows/app-c.yml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # install dependencies using the root folder
      - name: Install 📦
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      # run tests in apps/app-c folder
      # where its package.json file is located
      # with "npm run dev" command
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v5
        with:
          install: false
          working-directory: apps/app-c
          start: npm run dev
          # wait for the Next.js app to respond
          # before starting Cypress tests
          wait-on: 'http://localhost:3000'
