name: app-b
on:
  push:
    # run this workflow when files inside app-b change
    # or this workflow changes
    # or the root package.json changes
    paths:
      - 'apps/app-b/**'
      - package.json
      - .github/workflows/app-b.yml
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      # install dependencies using the root folder
      - name: Install 📦
        uses: cypress-io/github-action@v5
        with:
          runTests: false

      # run tests in apps/app-b folder
      # where its package.json file is located
      # with "npm start" command
      - name: Cypress tests 🧪
        uses: cypress-io/github-action@v5
        with:
          install: false
          working-directory: apps/app-b
          start: npm start
